### ISSUE TITLE
Need to help!

### ISSUE THREAD

**Issue by Etwaswie** [RdecKa/SLAM-with-LEGO-Mindstorms#1]
Hi! I have a couple of questions about your work. What method was used here? Kalman filter or particle filter? How does it all work?
I don't quite understand the principle by which the next point is selected to move the robot.

**Comment by RdecKa** [comment]
Hey!

I came up with my own strategy for selecting the next point - it was simple to implement but fairly inefficient, I'm afraid.

Here's the idea:

The robot creates a 2D grid that stores information about the observed world - it's like a 2D map of the area. Each cell is an integer that describes the occupancy of a location: Negative integers indicate a free location, positive integers indicate an obstacle on that location. The higher the absolute value in a cell, the higher the probability that the map at that location is correct.

When choosing the next point, the robot searches for points on the map with unknown occupancy (= with values slightly below zero). It then chooses the closest such point as the next goal. However, if the robot notices that the path to that goal is *not* obstacle-free, it chooses a random unknown point as the next goal.

Does this answer your questions? Please let me know if you have any further questions.

**Comment by RdecKa** [comment]
I'm closing the issue now but let me know if you have more questions.
